### ISSUE TITLE
longcellpre fails after the isoform extraction step

### ISSUE THREAD

**Issue by bpuzek** [yuntianf/LongcellPre#6]
Dear @yuntianf,

I also ran a small test run with 25k reads from our dataset:
```
Rscript RunLongcellPre.R -f mydata_25kreads.fastq.gz -b barcodes.tsv.gz -t 3 -q 10X -g GRCh38.primary_assembly.genome.fa -n hg38
        --gtf gencode.v47.annotation.gtf -o mydata_25kreads -c 4 -m multicore
```

I am running into an error after the isoform extraction step.

Last lines of the log file:

```
Start to extract isoforms:
Isoform extraction took 13.15 secs

  Elapsed_Time_sec Total_RAM_Used_MiB Peak_RAM_Used_MiB
1             8.76                0.5              19.4
```
```
Error in `summarise()`:
ℹ In argument: `count = sum(count)`.
Caused by error in `sum()`:
! invalid 'type' (list) of argument
Backtrace:
     ▆
  1. ├─base::do.call(RunLongcellPre, args)
  2. ├─LongcellPre (local) `<fn>`(...)
  3. │ ├─base::do.call(reads_extract_bc, Param)
  4. │ └─LongcellPre (local) `<fn>`(...)
  5. │   └─LongcellPre:::adapter_dis(...)
  6. │     └─adapter_dis %>% group_by(needle) %>% ...
  7. ├─dplyr::summarise(., count = sum(count))
  8. ├─dplyr:::summarise.grouped_df(., count = sum(count))
  9. │ └─dplyr:::summarise_cols(.data, dplyr_quosures(...), by, "summarise")
 10. │   ├─base::withCallingHandlers(...)
 11. │   └─dplyr:::map(quosures, summarise_eval_one, mask = mask)
 12. │     └─base::lapply(.x, .f, ...)
 13. │       └─dplyr (local) FUN(X[[i]], ...)
 14. │         └─mask$eval_all_summarise(quo)
 15. │           └─dplyr (local) eval()
 16. └─base::.handleSimpleError(...)
 17.   └─dplyr (local) h(simpleError(msg, call))
 18.     └─dplyr (local) handler(cnd)
 19.       └─rlang::abort(message, class = error_class, parent = parent, call = error_call)
 ```

Any ideas on what could be causing this issue, have you seen this before?

All the best,
Barbara

**Comment by yuntianf** [comment]
Hi Barbara,

I just checked the functions, this error is due to in a recent update I add some default parameters for the pipeline which conflit the parameters in the functions. I have fixed this bug and it should work properly now.

**Comment by bpuzek** [comment]
Dear @yuntianf,

thanks a lot for addressing this so quickly. Unfortunately, even after the latest update I still get the same error. Let me know if I can provide any extra info that could help.

Barbara

**Comment by bpuzek** [comment]
Hi, 

yes, I also updated that file.
